# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nestorcortes/Desktop/GH/chip8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nestorcortes/Desktop/GH/chip8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nestorcortes/Desktop/GH/chip8/CMakeFiles /Users/nestorcortes/Desktop/GH/chip8//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nestorcortes/Desktop/GH/chip8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myEmulator

# Build rule for target.
myEmulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myEmulator
.PHONY : myEmulator

# fast build rule for target.
myEmulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/build
.PHONY : myEmulator/fast

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Speaker.o: src/Speaker.cpp.o
.PHONY : src/Speaker.o

# target to build an object file
src/Speaker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Speaker.cpp.o
.PHONY : src/Speaker.cpp.o

src/Speaker.i: src/Speaker.cpp.i
.PHONY : src/Speaker.i

# target to preprocess a source file
src/Speaker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Speaker.cpp.i
.PHONY : src/Speaker.cpp.i

src/Speaker.s: src/Speaker.cpp.s
.PHONY : src/Speaker.s

# target to generate assembly for a file
src/Speaker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Speaker.cpp.s
.PHONY : src/Speaker.cpp.s

src/Unit_Tests/chip8_Test.o: src/Unit_Tests/chip8_Test.cpp.o
.PHONY : src/Unit_Tests/chip8_Test.o

# target to build an object file
src/Unit_Tests/chip8_Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Unit_Tests/chip8_Test.cpp.o
.PHONY : src/Unit_Tests/chip8_Test.cpp.o

src/Unit_Tests/chip8_Test.i: src/Unit_Tests/chip8_Test.cpp.i
.PHONY : src/Unit_Tests/chip8_Test.i

# target to preprocess a source file
src/Unit_Tests/chip8_Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Unit_Tests/chip8_Test.cpp.i
.PHONY : src/Unit_Tests/chip8_Test.cpp.i

src/Unit_Tests/chip8_Test.s: src/Unit_Tests/chip8_Test.cpp.s
.PHONY : src/Unit_Tests/chip8_Test.s

# target to generate assembly for a file
src/Unit_Tests/chip8_Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/Unit_Tests/chip8_Test.cpp.s
.PHONY : src/Unit_Tests/chip8_Test.cpp.s

src/chip8.o: src/chip8.cpp.o
.PHONY : src/chip8.o

# target to build an object file
src/chip8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/chip8.cpp.o
.PHONY : src/chip8.cpp.o

src/chip8.i: src/chip8.cpp.i
.PHONY : src/chip8.i

# target to preprocess a source file
src/chip8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/chip8.cpp.i
.PHONY : src/chip8.cpp.i

src/chip8.s: src/chip8.cpp.s
.PHONY : src/chip8.s

# target to generate assembly for a file
src/chip8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/chip8.cpp.s
.PHONY : src/chip8.cpp.s

src/cpu.o: src/cpu.cpp.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/keyboard.o: src/keyboard.cpp.o
.PHONY : src/keyboard.o

# target to build an object file
src/keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/keyboard.cpp.o
.PHONY : src/keyboard.cpp.o

src/keyboard.i: src/keyboard.cpp.i
.PHONY : src/keyboard.i

# target to preprocess a source file
src/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/keyboard.cpp.i
.PHONY : src/keyboard.cpp.i

src/keyboard.s: src/keyboard.cpp.s
.PHONY : src/keyboard.s

# target to generate assembly for a file
src/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myEmulator.dir/build.make CMakeFiles/myEmulator.dir/src/keyboard.cpp.s
.PHONY : src/keyboard.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... myEmulator"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Speaker.o"
	@echo "... src/Speaker.i"
	@echo "... src/Speaker.s"
	@echo "... src/Unit_Tests/chip8_Test.o"
	@echo "... src/Unit_Tests/chip8_Test.i"
	@echo "... src/Unit_Tests/chip8_Test.s"
	@echo "... src/chip8.o"
	@echo "... src/chip8.i"
	@echo "... src/chip8.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/keyboard.o"
	@echo "... src/keyboard.i"
	@echo "... src/keyboard.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

