/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.28.1-g7fec034 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.28.1-g7fec034"
#endif
#define SDL_REVISION_NUMBER 0
